name: Node.js CI

on:
  push:
    branches: [ main ]
    
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configura Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instala dependências
        run: npm install

      - name: Compila TypeScript
        run: npm run build

      - name: Testa build
        run: node dist/server.js

      - name: Testa o servidor
        env:
          PORT: ${{ env.PORT || 3000 }}
        run: |
          echo "Iniciando servidor na porta $PORT"
          npm run build
          node dist/server.js --port=$PORT &
          sleep 3
          echo "Testando conexão em http://localhost:$PORT/ping"
          curl -I "http://localhost:$PORT/ping"
